FROM ubuntu

#Entrypoint por defecto
ENTRYPOINT ["/bin/cat"]

#CMD no es por defecto, se lo indicamos nosotros
CMD ["/etc/os-release"]


# El ENTRYPOINT siempre se ejecuta el CMD lo podemos añadir el comando