FROM composer as backend

WORKDIR /app

COPY . /app

RUN composer install \
    --ignore-plataform-reqs \
    --no-ansi \
    --no-dev \
    --no-interaction \
    --no-scripts

FROM php:7.2-apache

RUN pecl install xdebug-2.6.0 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install pdo pdo_mysql

WORKDIR /app

# Con esto solo coje las dependencias que se encuentran en /app y no es necesario instalar composer
COPY --from=backend /app /var/www/html/
COPY php.ini /usr/local/etc/php/php.ini
